// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Xe2r3CiyedzrBdlbUO5QfUUL3ej9gRs',
    appId: '1:519538121078:web:77fc420ab2038f278d8257',
    messagingSenderId: '519538121078',
    projectId: 'purpleace',
    authDomain: 'purpleace.firebaseapp.com',
    storageBucket: 'purpleace.firebasestorage.app',
    measurementId: 'G-HDCPBT8QZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-u6oayRPVrgN6SSrK8HOROV7TZU9-QDM',
    appId: '1:519538121078:android:4f020ff6eb224f738d8257',
    messagingSenderId: '519538121078',
    projectId: 'purpleace',
    storageBucket: 'purpleace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTRrhYLGkeVqb_85uAGKk6_BEdVx33UvE',
    appId: '1:519538121078:ios:5a5e570864959be28d8257',
    messagingSenderId: '519538121078',
    projectId: 'purpleace',
    storageBucket: 'purpleace.firebasestorage.app',
    iosBundleId: 'com.example.purpleace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTRrhYLGkeVqb_85uAGKk6_BEdVx33UvE',
    appId: '1:519538121078:ios:5a5e570864959be28d8257',
    messagingSenderId: '519538121078',
    projectId: 'purpleace',
    storageBucket: 'purpleace.firebasestorage.app',
    iosBundleId: 'com.example.purpleace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Xe2r3CiyedzrBdlbUO5QfUUL3ej9gRs',
    appId: '1:519538121078:web:a5b47efae12de5cd8d8257',
    messagingSenderId: '519538121078',
    projectId: 'purpleace',
    authDomain: 'purpleace.firebaseapp.com',
    storageBucket: 'purpleace.firebasestorage.app',
    measurementId: 'G-XGBC8V9DBX',
  );
}
